// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lista_presenca.Models;

namespace lista_presenca.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20190419221453_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lista_presenca.Models.People", b =>
                {
                    b.Property<int>("matricula")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("curso")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("idade")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnType("varchar(2)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("semestre")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("matricula");

                    b.ToTable("Peoples");
                });
#pragma warning restore 612, 618
        }
    }
}
